server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/assisjrs/warmup/
          basedir: backend/configserver/src/main/resources

          #uri: https://github.com/rafaelcam/delivery-configs
          #delivery-sample-config

